name: Publish Package
on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run npm-publish
      - run: npm publish --access public

  github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          package-manager-cache: false
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@bothimtv'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run gh-publish
      - run: npm publish
